image_width: 2592
image_height: 1944
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [11944.7551 ,     0.     ,  1303.59765,
             0.     , 11497.15763,   850.97593,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-3.158534, 96.249521, 0.048993, -0.035457, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [11766.30176,     0.     ,  1284.35346,     0.     ,
             0.     , 11381.80469,   865.08124,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
